#!/bin/bash

declare octocov_bin=octocov

if [[ -x ./octocov ]]; then
	octocov_bin=./octocov
fi

echo octocov badge coverage '>' ./reports/.octocov-coverage.svg
${octocov_bin} badge coverage > ./reports/.octocov-coverage.svg
printf "\n"

echo octocov badge ratio '>' ./reports/.octocov-ratio.svg
${octocov_bin} badge ratio > ./reports/.octocov-ratio.svg
printf "\n"
printf "\n"
