#!/bin/bash

main()
{
	go generate ./...

	echo gotest -v -covermode=count -coverprofile=./reports/.coverage.out -cover ./...
	time gotest -v -covermode=count -coverprofile=./reports/.coverage.out -cover ./...
	printf "\n"

	# go install github.com/axw/gocov/gocov@latest

	echo gocov convert ./reports/.coverage.out '|' jq --sort-keys . '>' .coverage.json
	time gocov convert ./reports/.coverage.out | jq --sort-keys . > .coverage.json
	printf "\n"

	echo jq . .coverage.json '|' gocov annotate -ceiling 100 - '|' tee reports/coverage-annotations.txt
	time jq . .coverage.json | gocov annotate -ceiling 100 - | tee reports/coverage-annotations.txt
	printf "\n" | tee -a reports/coverage-annotations.txt

	echo jq . .coverage.json '|' gocov report '|' tee reports/coverage-summary.txt
	time jq . .coverage.json | gocov report | tee reports/coverage-summary.txt
	printf "\n"
}

time main

echo git restore ./cmd/*/.version.txt
time git restore ./cmd/*/.version.txt
printf "\n"
