#
# https://github.com/get-woke/woke-action-reviewdog
# https://github.com/get-woke/woke-action
#

name: Woke Workflow
on:
  - pull_request

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Woke with Reviewdog
        uses: get-woke/woke-action-reviewdog@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need. GitHub Status Check won't become failure with warning.
          level: error
          # Enable this to fail the check when violations are found
          fail-on-error: true
